# Basics of Python - Part 2

In this part of the tutorial, we will look at containers that stores information in Python. We will cover lists, tuples, sets and dictionaries here. They could be mutable or immutable; unordered or ordered. 

First of all, we should know the difference between mutable and immutable objects. A mutable object means that they can be changed once created. Lists, sets are mutable objects;  you can add new items or remove items from it. 

On the other hand, immutable objects cannot be changed once created. Strings, numbers are tuples are immutable objects.

## 1. Lists

Lists are included in Sequence Types in Python and they are mutable. Lists are one of my favorite objects in Python; I even use them a lot to solve many mathematical problems, as we will see in an example below. We create lists with square brackets, [ ]. Lists are mutable, ordered objects. Ordered means they store elements in an ordered way (i.e., each element has a position) and you can look at the specific range of elements in a set if you like. I should also mention that in Python, the indexing start from 0 meaning that the position of the first item is always 0. 

Tuples are immutable, so their content cannot be changed once created. That would be very useful in some applications, as well. 

Please refer to https://docs.python.org/2/library/stdtypes.html#typesseq for a more comprehensive coverage.

In [0]:
#you could create an empty list by typing [] or list().
lst1=[]
lst2=list()

print(lst1)
print(lst2)


#Let's define list a.
my_list=["a", "b", "c", "d"]

print(my_list)

#There are 4 elements in the set a. You can get that information by len() function.
print("There are {} elements in my_list.".format(len(my_list)))

#to add a new element to the end of this list use .append() at the end of my_list
my_list.append("e")

print(my_list)

#now lets remove the third element from this list:
my_list.pop(2)   # recall that ordering starts with 0 in Python.

#now, my_list doesn't have that element since it is removed.
print(my_list)

#to replace an element in this list, assign a new value to that particular element.
#Let's change the second element "b" assign a new value "this is new instead of b"
my_list[1]="this is new instead of b"

print(my_list)

[]
[]
['a', 'b', 'c', 'd']
There are 4 elements in my_list.
['a', 'b', 'c', 'd', 'e']
['a', 'b', 'd', 'e']
['a', 'this is new instead of b', 'd', 'e']

In [0]:
#Practice what you learned with the following lists. Feel free to check whatever you like to understand lists better.

lst=["pencil","pen","notebook","book","glasses","computer","eraser"]

lst[2]

my_list=[1,2,3,4,5,6,7,8,9,10,11,12]

my_list.append(10)

my_list[10]

11

### Accessing elements of list and slicing

In [0]:
my_list=["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"]

#To get the element in a given specific position we again use square brackets []. 
# For example, the first item in this list can be obtained by a[0].
print(my_list[0])
print("The third element of this list is {}".format(my_list[2]))

print("---------------------------------------")

#To get the last element, you could use [-1]
print(my_list[-1])

#You could get elements that are in a particular range.
print(my_list[2:4]) #this would print elements starting with position 2 but not including the element in position 4.

#We could slice from the beginning, and taking the first three elements...
print(my_list[:3])

#... or get all elements starting with position number 3
print(my_list[3:])

#we could get all elements in a particular pattern:
print(my_list[3::2]) #start from the 3rd element, run to the end, by skipping one element.

a
The third element of this list is c
---------------------------------------
j
['c', 'd']
['a', 'b', 'c']
['d', 'e', 'f', 'g', 'h', 'i', 'j']
['d', 'f', 'h', 'j']

### Sorting elements in a list

In [0]:
#Let's consider the list below.
lst=[2,1,3,5,4]

#let's sort its elements. First of all, to be able to sort, all of them must be the same typel.
#Default is sorting it in an increasing order.
print(sorted(lst))

#if you want to sort it in a descending order, you should mention that.
print(sorted(lst, reverse=True))

#you could sort list of strings as well.
lst2=['bananas', 'apples', 'oranges', 'apricots']
print(sorted(lst2))

[1, 2, 3, 4, 5]
[5, 4, 3, 2, 1]
['apples', 'apricots', 'bananas', 'oranges']

### List Comprehensions

Another way of creating new lists by performing the same thing for every member of the list is done by list comprehensions. But for this, we need to know about for loops. Therefore, this will be given after for loops in the next tutorial.

## 2. Tuples

Like lists, tuples are ordered objects. But unlike lists, they are immutable, i.e., they cannot be changed once created; adding new items or changing an item or removing items from it would create errors.

In [0]:
#To create an empty tuple you can use tuple() or (). You could also turn a list into a tuple.
lst=['a','b','c','d', 'e']
my_tuple=tuple(lst)
print(my_tuple)

#length of tuple can be found by len()
print(len(my_tuple))

'''Like lists or strings, tuples support indexing or slicing.'''

#You can access a specific item in the tuple:
print("The fourth item in my tuple is {}.".format(my_tuple[3]))

#You can get a range of elements in the tuple:
print(my_tuple[1:3]) #Note that item with position=3 is not included in the answer.


'''Unlike lists, you cannot add a new element or replace an element in a tuple. This is due to the fact that
tuples are immutable.'''

print("----------------------------")

#If you try .append() you will get an AttributeError. Please uncomment below and see it for yourself.
#my_tuple.append(3)

#If you try to replace an element in a tuple, you will get a TypeError. Please uncomment below and see it for yourself.
#my_tuple[1]='a'

('a', 'b', 'c', 'd', 'e')
5
The fourth item in my tuple is d.
('b', 'c')
----------------------------

In [0]:
#Tuple packing, unpacking
#We could define two things by using tuples without using (), as below. This could be very useful when writing longer codes.

x,y=1,2

x

1

## 3. Sets

Unlike lists or tuples, sets are unordered collection of unique elements. However, they are mutable like lists. We use curly brackets { } for sets. Please look at https://docs.python.org/2/library/sets.html?highlight=set#module-sets for details.

In [0]:
#We could create an empty set by using set() function. 
set1=set()

#add new elements to set1.
set1.add('a')
set1.add('b')
set1.add('c')
set1.add('d')

#As you can see from the output, the set is unordered unlike lists.
print(set1)

#length of a set can be found by len()
print(len(set1))


#remove an element from set1.
set1.remove('b')

print(set1)

#Since they are unordered, they don't support indexing. If you want to access a particular position, it will give a TypeError.
#Please uncomment and see it yourself.
#print(set1[2])

{'c', 'd', 'b', 'a'}
4
{'c', 'd', 'a'}

In [0]:
set2={'a', 'b', 'c', 'd'}

#test membership of an element:
print(2 in set2)
print('a' in set2)
print(3 not in set2)

False
True
True

In [0]:
#A cool way of using sets would be getting only distinct elements in a list.
#Let's say, we have the following list but we want to know what the distinct numbers are in this list. 
lst=[1,2,3,4,2,3,4,5,4, 5, 5, 2, 1, 3]

#So, we first create a set using this list. We simply use set() to do that.
new_set=set(lst)

#Then, the new set becomes
print(new_set)

#If we want to get back to a list, we use list() function.

distinct_lst=list(new_set)

print(distinct_lst)

{1, 2, 3, 4, 5}
[1, 2, 3, 4, 5]

## 4. Dictionaries

Sometimes, we may want to create a collection of elements where each item in this collection has a pair of elements; a key-value pair. Here, assign a particular value to each unique key. In this sense, dictionaries are mapping where each key is mapped to a a value. We use curly brackets, write each pair like key:value and separate them with commas. You cannot use mutable objects (lists, sets) for keys as they are 'unhashable' type.  In addition, dictionaries are also unhashable. However, tuples, strings, numbers would be ok for keys. As for values, we don't have any restrictions.

Like lists, they are mutable objects. You can add or remove elements from a dictinary. Please refer to https://docs.python.org/2/library/stdtypes.html#dict for a more comprehensive coverage.

In [0]:
#Ways of writing a dictionary:

dict1={"a":195, (1,2,3):"Chicago", 22: ['a', 'b', 'c']}

print(dict1)

#length of a dictionary can be found by len()
print(len(dict1))

#You have to enter the key value to access a particular value associated with that key.
print(dict1['a'])

#You could use the following way to write your dictionary:
dict2=dict(apples=1, bananas=2, cherries=3)

print(dict2)

#to add a new key:value pair, you could use .get(key,value)
dict2['oranges']=dict2.get('oranges',4)

print(dict2)

{'a': 195, (1, 2, 3): 'Chicago', 22: ['a', 'b', 'c']}
3
195
{'apples': 1, 'bananas': 2, 'cherries': 3}
{'apples': 1, 'bananas': 2, 'cherries': 3, 'oranges': 4}

In [0]:
#to get all the keys of a dictionary, use .keys()
print(dict1.keys())

#to get all the values of a dictionary, use .values()
print(dict1.values())

#to get all the values of a dictionary, use .items()
print(dict1.items())

#Note that .items() lists each key:value pair as tuples. This gives us an access to reach to keys and values when we need it.

print('----------------------------------------------')

'''Let's say, we want to create two lists, one for keys of dict1, another for values of dict1. '''

#We first create two empty lists:
keys_list=[]
values_list=[]

#Now, let's iterate over dict1.items() and get the elements we want:
for k, v in dict1.items():
    keys_list.append(k)
    values_list.append(v)

print(keys_list)

print(values_list)

dict_keys(['a', (1, 2, 3), 22])
dict_values([195, 'Chicago', ['a', 'b', 'c']])
dict_items([('a', 195), ((1, 2, 3), 'Chicago'), (22, ['a', 'b', 'c'])])
----------------------------------------------
['a', (1, 2, 3), 22]
[195, 'Chicago', ['a', 'b', 'c']]

## 5. Strings

We already saw how we could use strings in Python to express words. However, they can also be considered as a Sequence type object as they also store information, characters. Like lists, they are ordered and support indexing and slicing. Unlike lists, they are immutable, you cannot change them once created. 

There are many string operations widely used in Data Science; if you are interested in this, you may want to check documentation for many useful things that you could use with strings. 

If you want to see a cool way that I use strings to solve many math problems, please check out the example at the end of the tutorial for for statements. In my opinion, this would be one of the new type of thinking that technology brings.

In [0]:
my_string="Today is a beautiful day, isn't it?"

#to get the 5th character, you could specify the position.
print(my_string[4])

#to get the first word, you specify the length by giving a range.
print(my_string[0:5])   #Recall that 5th position character (i in this sentence) is not included.

#Starting from the 2nd position, you could get every third character until the end of the sentence. 
print(my_string[2::3])

y
Today
d  buf yi'i

In [0]:
#Length of a string can be found by using len()
print(len(my_string))

'''
#Recall that once you use double quotes, every character would be a string type, including 
#symbols and whitespaces. That is why the length of this string is 35. That is why there is a need
#of data cleaning in Data Science before you could work on a Data Science project. Typos or punctuations
#would make two strings different to a computer.
'''

x="Math 195"
y="Math195"
z="math 195"

print(x==y)
print(x==z)
print(y==z)

35
False
False
False